# Your Website Title
title: Vivek Mehta

# Your Website URL
url: 'http://vivekmehta27.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Vivek Mehta
tagline: Research Scholar in Computer Science 
pic: Vivek_.jpg # profile.png can be found at /assets/images/profile.png
description: 
description_tiny: 
email: vivekmehta27@gmail.com
website: vivekmehta27.github.io # do not add http://
linkedin: vivek-mehta27
github: vivekmehta27
twitter: 'vivekmehta27'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm