# Your Website Title
title: Vivek Mehta

# Your Website URL
url: 'http://vivekmehta27.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Vivek Mehta
tagline: Machine Learning Researcher 
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Full Stack Developer, IoT, Reverse Engineering
description_tiny: 'Home: +60-4 | Studied: +1-408 | Work: +60-3'
email: vivekmehta27@gmail.com
website: vivekmehta27.github.io # do not add http://
linkedin: realmelvinchng
github: vivekmehta27
twitter: '@realmelvinchng'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm